// Regenerates app/assets/css/themes.generated.css from the theme registry.
// Run via `npm run gen:themes` whenever a theme's seeds change. The output is committed so the
// build never depends on running this. jiti loads the TS sources (Nuxt ships it).
import { createJiti } from 'jiti';
import { writeFileSync } from 'node:fs';

const jiti = createJiti(import.meta.url);
const { THEMES } = await jiti.import('../app/theme/registry.ts');
const { renderCatalogCss } = await jiti.import('../app/theme/generate.ts');

const header = '/* GENERATED by `npm run gen:themes` from app/theme/registry.ts — do not edit by hand. */\n';
const out = new URL('../app/assets/css/themes.generated.css', import.meta.url);
writeFileSync(out, header + renderCatalogCss(THEMES));
console.log(`Wrote ${THEMES.filter((t) => !t.builtin).length} generated theme(s) to ${out.pathname}`);
