name: Unit Tests

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/run-tests.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: kenku
          POSTGRES_PASSWORD: kenku_test
          POSTGRES_DB: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore dependencies
        run: dotnet restore ./Kenku.sln

      - name: Build the solution
        run: dotnet build ./Kenku.sln --configuration Release --no-restore -p:DisableOpenApiGeneration=true -m:1

      - name: Run unit tests with report
        run: dotnet test ./Tests/Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v6
        with:
          name: TestResults
          path: ./api/Tests/TestResults/TestResults.trx
